// Generated by CoffeeScript 1.6.2
module.exports = function(U) {
  return U.DropView = Em.View.extend({
    classNames: 'component upload drop'.w(),
    classNameBindings: 'over'.w(),
    over: false,
    didInsertElement: function() {
      var el;

      this._super();
      el = this.$()[0];
      this.set('el', el);
      el.addEventListener('dragenter', this.ondragenter.bind(this), false);
      el.addEventListener('dragover', this.ondragover.bind(this), false);
      el.addEventListener('dragleave', this.ondragleave.bind(this), false);
      return el.addEventListener('drop', this.ondrop.bind(this), false);
    },
    ondragenter: function(e) {
      return this.set('over', true);
    },
    ondragover: function(e) {
      e.preventDefault();
      return false;
    },
    ondragleave: function(e) {
      return this.set('over', false);
    },
    ondrop: function(e) {
      var file, _i, _len, _ref, _results;

      e.stopPropagation();
      e.preventDefault();
      this.set('over', false);
      _ref = e.dataTransfer.files;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        _results.push(U.Upload.create().upload(file));
      }
      return _results;
    }
  });
};
