// Generated by CoffeeScript 1.6.1

module.exports = function(to) {
  var U;
  require('ember');
  U = Em.Namespace.create({
    to: to
  });
  require('./upload')(U);
  require('./progress')(U);
  require('./input')(U);
  require('./drop')(U);
  return U;
};
