// Generated by CoffeeScript 1.6.2
module.exports = function(U) {
  var barView, compile;

  compile = Em.Handlebars.compile;
  /*
  .bar view
  */

  barView = Em.View.extend({
    attributeBindings: 'style'.w(),
    classNames: 'bar'.w(),
    init: function() {
      this._super();
      return U.addObserver('upload.progress', this.onprogress.bind(this));
    },
    onprogress: function() {
      var progress, style;

      progress = U.get('upload.progress');
      style = "width: " + progress + "%";
      return this.set('style', style);
    }
  });
  /*
  .bar wrapper
  */

  return U.ProgressView = Em.ContainerView.extend({
    childViews: 'barView'.w(),
    barView: barView,
    classNames: 'component upload progress info'.w(),
    classNameBindings: 'show'.w(),
    show: false,
    init: function() {
      this._super();
      U.addObserver('upload.progress', this.onprogress.bind(this));
      U.addObserver('upload.abort', this.onabort.bind(this));
      return U.addObserver('upload.error', this.onerror.bind(this));
    },
    onprogress: function() {
      var progress;

      progress = U.get('upload.progress');
      if (progress === 100) {
        return this.set('show', false);
      } else if (progress) {
        return this.set('show', true);
      }
    },
    onabort: function() {
      var abort;

      abort = U.get('upload.abort');
      if (abort) {
        return this.set('show', false);
      }
    },
    onerror: function() {
      var error;

      error = U.get('upload.error');
      if (error) {
        return this.set('show', false);
      }
    }
  });
};
