// Generated by CoffeeScript 1.6.2
module.exports = function(U) {
  return U.Upload = Em.Object.extend({
    init: function() {
      this._super();
      return U.set('upload', this);
    },
    upload: function(file) {
      var body, req, to;

      to = U.get('to');
      file.slice = file.slice || file.webkitSlice;
      body = new FormData;
      body.append('file', file);
      req = this.req = new XMLHttpRequest;
      req.upload.onprogress = this.onprogress.bind(this);
      req.onerror = this.onerror.bind(this);
      req.onabort = this.onabort.bind(this);
      req.open('POST', to);
      return req.send(body);
    },
    onloadstart: function(e) {
      return this.set('loadstart', true);
    },
    onprogress: function(e) {
      var progress;

      progress = void 0;
      if (e.lengthComputable) {
        progress = e.loaded / e.total * 100;
      }
      return this.set('progress', progress);
    },
    onload: function(e) {
      return this.set('load', true);
    },
    onerror: function(e) {
      return this.set('error', true);
    },
    onabort: function(e) {
      return this.set('abort', true);
    },
    onloadend: function(e) {
      return this.set('loadend', true);
    }
  });
};
